

#Module      : LABEL
#Description : Terraform label module variables
variable "name" {
  type        = string
  default     = "GuardDutyEnablerLambda"
  description = "Name  (e.g. `app` or `cluster`)."
}

variable "repository" {
  type        = string
  default     = null
  description = "Terraform current module repo"
}

variable "environment" {
  type        = string
  default     = "test"
  description = "Environment (e.g. `prod`, `dev`, `staging`)."
}

variable "label_order" {
  type        = list(any)
  default     = ["environment", "name"]
  description = "Label order, e.g. `name`,`application`."
}

variable "attributes" {
  type        = list(any)
  default     = []
  description = "Additional attributes (e.g. `1`)."
}

variable "managedby" {
  type        = string
  default     = "test"
  description = "ManagedBy,"
}

variable "enable" {
  type        = bool
  default     = true
  description = "Whether to create lambda function."
}

variable "create_layers" {
  type        = bool
  default     = false
  description = "Flag to control creation of lambda layers."
}

variable "role_name" {
  type        = string
  default     = "GuardDutyEnablerRole"
  description = "Name  (e.g. `app` or `cluster`)."
}

variable "assume_role" {
  type        = string
  default     = "AWSControlTowerExecution"
  description = "What role should be assumed in accounts to enable GuardDuty? The Default is AWSControlTowerExecution for a Control Tower environment."
}

variable "control_tower_management_account" {
  type    = string
  default = null
}

variable "security_account_id" {
  type    = string
  default = ""
}

variable "organization_id" {
  type    = string
  default = ""
}

variable "region_filter" {
  type    = string
  default = "ControlTower"
}

variable "aws_partition" {
  type    = string
  default = ""
}

variable "runtime" {
  type        = string
  default     = "python3.7"
  description = "Runtimes."
}


variable "handler" {
  type        = string
  default     = "guardduty_enabler.lambda_handler"
  description = "The function entrypoint in your code."
}

variable "actions" {
  type        = list(any)
  default     = ["lambda:InvokeFunction", "lambda:InvokeFunction", "lambda:InvokeFunction"]
  description = "The AWS Lambda action you want to allow in this statement. (e.g. lambda:InvokeFunction)."
}

variable "principals" {
  type        = list(any)
  default     = ["sns.amazonaws.com", "events.amazonaws.com", "events.amazonaws.com"]
  description = "The principal who is getting this permission. e.g. s3.amazonaws.com, an AWS account ID, or any valid AWS service principal such as events.amazonaws.com or sns.amazonaws.com."
}

variable "filename" {
  type        = string
  default     = "../code/guardduty_enabler.zip"
  description = "The path to the function's deployment package within the local filesystem. If defined, The s3_-prefixed options cannot be used."
}

variable "enabled" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create sns module."
}

variable "enable_sns" {
  type        = bool
  default     = false
  description = "Boolean indicating whether or not to create sns."
}

variable "enable_topic" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create topic."
}

variable "enable_subscription" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create subscription."
}

variable "sns_name" {
  type        = string
  default     = "GuardDutyEnablerTopic"
  description = "The display name for the SNS topic."
}

variable "display_name" {
  type        = string
  default     = "GuardDuty_Enabler"
  description = "The display name for the SNS topic."
}

variable "topic_name" {
  type        = string
  default     = "GuardDutyEnablerTopic"
  description = "The friendly name for the SNS topic. By default generated by Terraform."
}

variable "protocol" {
  type        = string
  default     = "lambda"
  description = "The protocol to use. The possible values for this are: sqs, sms, lambda, application."
}

variable "compliance_frequency" {
  type        = number
  default     = 60
  description = "How frequently (in minutes, between 1 and 3600, default is 60) should organizational compliance be checked?"
}
