variable "region" {
  default = "us-east-1"
}

#Module      : LABEL
#Description : Terraform label module variables
variable "name" {
  type        = string
  default     = "GuardDutyEnablerLambda"
  description = "Name  (e.g. `app` or `cluster`)."
}

variable "repository" {
  type        = string
  default     = "https://github.com/clouddrove/terraform-aws-lambda"
  description = "Terraform current module repo"
}

variable "environment" {
  type        = string
  default     = "test"
  description = "Environment (e.g. `prod`, `dev`, `staging`)."
}

variable "label_order" {
  type        = list(any)
  default     = ["environment", "name"]
  description = "Label order, e.g. `name`,`application`."
}

variable "attributes" {
  type        = list(any)
  default     = []
  description = "Additional attributes (e.g. `1`)."
}

variable "managedby" {
  type        = string
  default     = "hello@clouddrove.com"
  description = "ManagedBy, eg 'CloudDrove'."
}

variable "enable" {
  type        = bool
  default     = true
  description = "Whether to create lambda function."
}

variable "role_name" {
  type        = string
  default     = "GuardDutyEnablerRole"
  description = "Name  (e.g. `app` or `cluster`)."
}

variable "assume_role" {
  type        = string
  default     = "AWSControlTowerExecution"
  description = "What role should be assumed in accounts to enable GuardDuty? The Default is AWSControlTowerExecution for a Control Tower environment."
}

variable "aws_account_id" {
  type    = string
  default = ""
}

variable "organization_id" {
  type    = string
  default = ""
}

variable "aws_partition" {
  type    = string
  default = ""
}

variable "runtime" {
  type        = string
  default     = "python3.7"
  description = "Runtimes."
}


variable "lambda_handler" {
  default = "guardduty_enabler.lambda_handler"
}

variable "memory_size" {
  type        = number
  default     = 128
  description = "Amount of memory in MB your Lambda Function can use at runtime. Defaults to 128."
}

variable "timeout" {
  type        = number
  default     = 300
  description = "The amount of time your Lambda Function has to run in seconds. Defaults to 3."
}

variable "variables" {
  type        = map(any)
  default     = null
  description = "A map that defines environment variables for the Lambda function."
}

variable "actions" {
  type        = list(any)
  default     = ["lambda:InvokeFunction"]
  description = "The AWS Lambda action you want to allow in this statement. (e.g. lambda:InvokeFunction)."
}

variable "principals" {
  type        = list(any)
  default     = ["events.amazonaws.com", "sns.amazonaws.com"]
  description = "The principal who is getting this permission. e.g. s3.amazonaws.com, an AWS account ID, or any valid AWS service principal such as events.amazonaws.com or sns.amazonaws.com."
}

variable "filename" {
  default     = "./code/guardduty_enabler.zip"
  description = "The path to the function's deployment package within the local filesystem. If defined, The s3_-prefixed options cannot be used."
}

variable "s3_buckets" {
  type        = list(any)
  default     = ["s3_bucket_name"]
  description = "The S3 bucket contains the guardduty_enabler.zip file for the GuardDutyEnabler lambda function."
}

variable "s3_keies" {
  type        = list(any)
  default     = ["./code/guardduty_enabler.zip"]
  description = "The S3 key of an object containing the function's deployment package. Conflicts with filename."
}

variable "statement_ids" {
  type        = list(any)
  default     = ["AllowExecutionFromCloudWatch"]
  description = "A unique statement identifier. By default generated by Terraform. "
}

variable "enabled" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create sns module."
}

variable "enable_sns" {
  type        = bool
  default     = false
  description = "Boolean indicating whether or not to create sns."
}

variable "enable_topic" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create topic."
}

variable "enable_subscription" {
  type        = bool
  default     = true
  description = "Boolean indicating whether or not to create subscription."
}

variable "sns_name" {
  type        = string
  default     = "GuardDuty_SNS"
  description = "The display name for the SNS topic."
}

variable "display_name" {
  type        = string
  default     = "GuardDuty_Enabler"
  description = "The display name for the SNS topic."
}

variable "topic_name" {
  type        = string
  default     = "GuardDutyEnablerTopic"
  description = "The friendly name for the SNS topic. By default generated by Terraform."
}

variable "protocol" {
  type        = string
  default     = "lambda"
  description = "The protocol to use. The possible values for this are: sqs, sms, lambda, application."
}

variable "compliance_frequency" {
  type        = number
  default     = 60
  description = "How frequently (in minutes, between 1 and 3600, default is 60) should organizational compliance be checked?"
}
