variable "region" {
  default = "us-east-1"
}

#Module      : LABEL
#Description : Terraform label module variables
variable "name" {
  type        = string
  default     = "Macie"
  description = "Name  (e.g. `app` or `cluster`)."
}

variable "repository" {
  type        = string
  default     = "https://github.com/clouddrove/terraform-aws-lambda"
  description = "Terraform current module repo"
}

variable "environment" {
  type        = string
  default     = "test"
  description = "Environment (e.g. `prod`, `dev`, `staging`)."
}

variable "label_order" {
  type        = list(any)
  default     = ["environment", "name"]
  description = "Label order, e.g. `name`,`application`."
}

variable "attributes" {
  type        = list(any)
  default     = []
  description = "Additional attributes (e.g. `1`)."
}

variable "managedby" {
  type        = string
  default     = "hello@clouddrove.com"
  description = "ManagedBy, eg 'CloudDrove'."
}

# Module      : Lambda function
# Description : Terraform Lambda function module variables.

variable "enable" {
  type        = bool
  default     = true
  description = "Whether to create lambda function."
}

variable "runtime" {
  type        = string
  default     = "python3.9"
  description = "Runtimes."
}


variable "lambda_handler" {
  default = "index.lambda_handler"
}

variable "memory_size" {
  type        = number
  default     = 128
  description = "Amount of memory in MB your Lambda Function can use at runtime. Defaults to 128."
}

variable "timeout" {
  type        = number
  default     = 600
  description = "The amount of time your Lambda Function has to run in seconds. Defaults to 3."
}

variable "description" {
  type    = string
  default = "Lambda Function that is triggered by CloudFormation Custom Resource to Enable Amazon Macie by Default"
}

variable "create_iam_role" {
  type        = bool
  default     = true
  description = "Flag to control creation of iam role and its related resources."
}

variable "iam_role_arn" {
  type        = string
  default     = null
  description = "Iam Role arn to be attached to lambda function."
}

variable "source_file" {
  type        = string
  default     = null
  description = "Path of source file that is required to be converted in `.zip` file"
}

variable "filename" {
  default     = "./macie.zip"
  description = "The path to the function's deployment package within the local filesystem. If defined, The s3_-prefixed options cannot be used."
}

variable "enable_source_code_hash" {
  type        = bool
  default     = true
  description = "Whether to ignore changes to the function's source code hash. Set to true if you manage infrastructure and code deployments separately."
}

variable "variables" {
  type        = map(any)
  default     = null
  description = "A map that defines environment variables for the Lambda function."
}

variable "create_layers" {
  type        = bool
  default     = true
  description = "Flag to control creation of lambda layers."
}

variable "layers" {
  default     = null
  description = "List of Lambda Layer Version ARNs (maximum of 5) to attach to your Lambda Function."
}

variable "lambda_layer_name" {
  default = "cfnresponse"
}

variable "compatible_runtimes" {
  type        = list(any)
  default     = ["python3.9"]
  description = "A list of Runtimes this layer is compatible with. Up to 5 runtimes can be specified."
}

variable "version_description" {
  default = "v1.1.2 of cfnresponse"
}

variable "s3_buckets" {
  type        = list(any)
  default     = ["s3_bucket_name"]
  description = "The S3 bucket location containing the function's deployment package. Conflicts with filename. This bucket must reside in the same AWS region where you are creating the Lambda function."
}

variable "s3_keies" {
  type        = list(any)
  default     = ["./cfnresponse.zip"]
  description = "The S3 key of an object containing the function's deployment package. Conflicts with filename."
}

variable "statement_ids" {
  type        = list(any)
  default     = ["AllowExecutionFromCloudWatch"]
  description = "A unique statement identifier. By default generated by Terraform. "
}

variable "actions" {
  type        = list(any)
  default     = ["lambda:InvokeFunction"]
  description = "The AWS Lambda action you want to allow in this statement. (e.g. lambda:InvokeFunction)."
}

variable "principals" {
  type        = list(any)
  default     = ["events.amazonaws.com"]
  description = "The principal who is getting this permission. e.g. s3.amazonaws.com, an AWS account ID, or any valid AWS service principal such as events.amazonaws.com or sns.amazonaws.com."
}

variable "assume_role" {
  type        = string
  default     = "AWSControlTowerExecution"
  description = "What role should be assumed in accounts to enable GuardDuty? The Default is AWSControlTowerExecution for a Control Tower environment."
}

variable "aws_account_id" {
  type    = string
  default = ""
}

variable "organization_id" {
  type    = string
  default = ""
}
