name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  single-account:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/single-account/'
      aws_credentials: true
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
  networking:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/multi-account/networking'
      aws_credentials: true
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
  shared:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/multi-account/shared'
      aws_credentials: true
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
  dev:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/multi-account/dev'
      aws_credentials: true
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
